image: node:12.8.0
pipelines:
    pull-requests:
        feature/*:
            - step:
                  script:
                      - npm install
                      - npm run init
                      - npm run bundle
                      - npm run libtest
    branches:
        develop:
            - step:
                  script:
                      - npm install
                      - npm run init
                      - npm run bundle
                      - npm run libtest
