export enum ExecType {
    New = "New",
    PartialFill = "PartialFill",
    Fill = "Fill",
    Trade = "Trade",
    DoneForDay = "DoneForDay",
    Canceled = "Canceled",
    Replace = "Replaced",
    Stopped = "Stopped",
    Rejected = "Rejected",
    Suspended = "Suspended",
    Calculated = "Calculated",
    Expired = "Expired",
    PendingCancel = "PendingCancel",
    PendingNew = "PendingNew",
    PendingReplace = "PendingReplace",
    TradeCancel = "TradeCancel",
}
