import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";
import { ConfigService } from "./config/config.service";
import { INestApplication } from "@nestjs/common";
import { SwaggerModule, DocumentBuilder, SwaggerBaseConfig } from "@nestjs/swagger";
import { FastifyAdapter, NestFastifyApplication } from "@nestjs/platform-fastify";

import * as pjson from "../package.json";

function getSwaggerConfig(apiVersion: string): SwaggerBaseConfig {
  return new DocumentBuilder()
        .setBasePath(`api/${apiVersion}`)
        .setTitle(pjson.name)
        .setDescription("This is git server REST API documentation generated by swagger")
        .setVersion(pjson.version)
        .addTag("app")
        .build();
}

async function bootstrap() {
  const app: INestApplication = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
  const configService: ConfigService = app.get(ConfigService);
  const version = "v1";

  // set up global api prefix
  app.setGlobalPrefix(`api/${version}`);
  // set up swagger
  const swaggerConfig: SwaggerBaseConfig = getSwaggerConfig(version);
  const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup("api", app, document);
  // start app
  await app.listen(configService.port, configService.host);
}

bootstrap();
