#!/bin/sh

username=$1
password=$2
host=$3
folder=$4
statsdhost=$5

if [ "$1" = "help" ]; then
    echo "./run [username] [password] [host] [folder] [statsdhost]"
    exit 0;
fi;

payload='{"email":"'${username}'", "password":"'${password}'"}';
auth=$(curl -d "${payload}" -H "Content-Type: application/json" -X POST ${host}/api/v1/users/auth)
accessToken=$(node ./parse-auth-token.js ${auth})
echo "$accessToken"
export AUTH_TOKEN="$accessToken"
export TARGET_HOST="$host"
export DD_API_KEY=75ac1280f5939acb99b2b22f4b24362e
export PROJECT_FOLDER="$folder"
export STATSD_HOST="$statsdhost"
# artillery run "./$folder/rest.yaml"
artillery run "./$folder/socket.yaml"
