#!/bin/sh

cp -f ./scripts/hooks/pre-push-root ./.git/hooks/pre-push # copy water.txt into it

for i in ./.git/modules/packages/* # iterate over all files in current dir
do
    if [ -d "$i" ] # if it's a directory
    then
        cp -f ./scripts/hooks/pre-push "$i"/hooks # copy water.txt into it
    fi
done
